const teamData = [
  // 👑 LEADERSHIP TEAM
  {
    id: 101,
    name: "Javed Khan",
    role: "Founder & CEO",
    category: "leadership",
    img: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=900&auto=format&fit=crop&q=60",
    quote: "Innovation is not about following a roadmap; it's about building the road that others will follow. At Javtech, we build the path to your digital dominance.",
    description: "A true technology visionary with over a decade of experience leading digital transformation initiatives for global enterprises. His Zero-Failure work philosophy inspires the entire company to deliver products and solutions that set new benchmarks.",
  },
  {
    id: 102,
    name: "Aamil Khan",
    role: "Co-Founder & Manager",
    category: "leadership",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900&auto=format&fit=crop&q=60",
    quote: "We don't just build for today's needs—we engineer for tomorrow's possibilities, ensuring your business stays ahead of the digital curve.",
    description: "The technical powerhouse driving research and development efforts. With an impressive background in digital field, he ensures Javtech remains at the forefront of technological progress, designing future-proof systems.",
  },
  {
    id: 103,
    name: "Tabrez Khan",
    role: "Human Resources Manager",
    category: "leadership",
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900&auto=format&fit=crop&q=60",
    quote: "We don't just hire for skills; we recruit for passion and engineer for greatness",
    description: "The architect of Javtech's people-first strategy, specializing in talent acquisition, employee development, and organizational growth. He cultivates an environment of continuous learning and transparency.",
  },

  // 👨‍💻 TEAM MEMBERS
  {
    id: 1,
    name: "Sara Lamichhane",
    role: "Full Stack Developer",
    category: "team",
    img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=900&auto=format&fit=crop&q=60",
    description: "A true architect of scalable, powerful systems. With a keen eye for building robust back-end frameworks and seamless front-end integrations, she ensures every project runs smoothly and securely.",
  },
  {
    id: 2,
    name: "Barun Shrestha",
    role: "Full Stack Developer",
    category: "team",
    img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=900&auto=format&fit=crop&q=60",
    description: "Builds complex software ecosystems designed to expand effortlessly with your business. Balancing sophisticated database management with slick user interfaces.",
  },
  {
    id: 3,
    name: "Birendra Dhami",
    role: "Full Stack Developer",
    category: "team",
    img: "https://images.unsplash.com/photo-1521119989659-a83eee488004?w=900&auto=format&fit=crop&q=60",
    description: "The perfect blend of technical precision and elegant design. Known for his zero-failure approach, overseeing the entire development process.",
  },
  {
    id: 4,
    name: "Pushit Chaudhary",
    role: "Full Stack Developer",
    category: "team",
    img: "https://plus.unsplash.com/premium_photo-1671656349322-41de944d259b?w=900&auto=format&fit=crop&q=60",
    description: "A dynamic engineer who bridges the gap between high-performance back-end logic and pixel-perfect front-end artistry. Specializes in transforming complex concepts into captivating visual journeys.",
  },
  {
    id: 5,
    name: "Saurav Dhital",
    role: "Application Developer",
    category: "team",
    img: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=900&auto=format&fit=crop&q=60",
    description: "A specialist in crafting custom software programs tailored to unique client needs. Excels at translating complex business requirements into user-friendly applications.",
  },
  {
    id: 6,
    name: "Bishal Regmi",
    role: "Application Developer",
    category: "team",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=900&auto=format&fit=crop&q=60",
    description: "Focuses on application performance lifecycle. Expert at developing cross-platform solutions that maintain high-speed functionality across various environments.",
  },
  {
    id: 7,
    name: "Bhumika Bista",
    role: "Frontend Developer",
    category: "team",
    img: "https://images.unsplash.com/photo-1614204424926-196a80bf0be8?w=900&auto=format&fit=crop&q=60",
    description: "Believes that the best design is both beautiful and intuitive. Crafts user-friendly interfaces that remove friction and ensure every interaction feels natural.",
  },
  {
    id: 8,
    name: "Sadip Khatri",
    role: "Frontend Developer",
    category: "team",
    img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=900&auto=format&fit=crop&q=60",
    description: "Brings speed and precision to frontend development. Expertise in optimizing performance and ensuring flawless display across all devices.",
  },
  {
    id: 9,
    name: "Sahitya Bhattarai",
    role: "Content Writer",
    category: "team",
    img: "https://plus.unsplash.com/premium_photo-1682096252599-e8536cd97d2b?w=900&auto=format&fit=crop&q=60",
    description: "The voice behind Javtech's message. Specializes in turning complex tech ideas into clear, compelling stories that build brand authority and boost SEO.",
  },
];

export default teamData;